export default {
  ABOUT_HEADING: "HELLO HEADING",
  ABOUT_DESC: "SOME DESCRIPTION",

  SERVICES: "Services",
  FRONT_END: "FRONT END",
  FRONT_DESC: "FRONT END DESCRIPTION",

  BACK_END: "FRONT END",
  BACK_DESC: "FRONT END DESCRIPTION",

  ONLINE: "FRONT END",
  ONLINE_DESC: "FRONT END DESCRIPTION",
};
